### ISSUE TITLE
Migrate to Traefik v2

### ISSUE THREAD

**Issue by jacksgt** [vision-it/vision-traefik#5]
So, a few days ago Traefik v2 was released which introduces major breaking changes.
I don't think they will support v1.7 for much longer.

https://github.com/containous/traefik/releases/tag/v2.0.0

Migration Guide:

https://docs.traefik.io/migration/v1-to-v2/

**Comment by jacksgt** [comment]
https://github.com/vision-it/vision-traefik/tree/traefikv2

**Comment by jacksgt** [comment]
Good that we now have a staging cluster :-)

**Comment by martialblog** [comment]
Is this ready to test?

**Comment by jacksgt** [comment]
No, not at all. I'm still waiting for them to implement some fixes on v2.0, polish their docs etc.

**Comment by jacksgt** [comment]
See e.g. https://github.com/containous/traefik/issues/4863

**Comment by martialblog** [comment]
Working on it. Will be tracked internally

**Comment by jacksgt** [comment]
:tada: :clap: :100: :1st_place_medal:
